### PR TITLE
added Comonad instance.

### PR DESCRIPTION
**Pull request by wygulmage**
You'll probably want to check my work, so I left it in there.

Sorry about the messy diff; my editor deleted some trailing whitespace.

### CODE REVIEW

**Comment by conal** [comment]
Thanks for the pull request. I don't think this instance could satisfy my basic requirement, namely that the semantic function is a `Comonad` homomorphism. I've not played with `Comonad` homomorphisms, but I think they'd be defined as follows for a function `h`:

``` haskell
extract w == extract (h w)

h (fmap h (duplicate m)) = duplicate (h m)
```

In our case, `h = (!)` (the "semantic function").

Such homomorphisms prevent abstraction leaks and guarantee that the class laws hold, as described in my [TCM paper and talk](http://conal.net/papers/type-class-morphisms/).

**Comment by wygulmage** [comment]
Thanks, Conal; when I'm sure I have something that follows the denotational semantics, I'll make another pull request.

**Comment by wygulmage** [comment]
If I understand what you're saying, the new instance should preserve (!) as a homomorphism to the Control.Comonad instance for functions by treating `mempty` as a left- and right-'identity key'.

**Comment by wygulmage** [comment]
Would it be worth including `fmap . (!)` for semigroupoid composition of maps?

**Comment by conal** [comment]
Great idea!

**Pull request closed without merging**
